"""add_location_description_cover_to_events

Revision ID: b4244148af48
Revises: 2b317bc8e1cd
Create Date: 2026-02-05 05:40:33.886583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4244148af48'
down_revision = '2b317bc8e1cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('events', sa.Column('cover_image', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_faces_compreface_subject_id'), 'faces', ['compreface_subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faces_compreface_subject_id'), table_name='faces')
    op.drop_column('events', 'cover_image')
    op.drop_column('events', 'description')
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
