"""increase_guest_session_token_length

Revision ID: fb5fead30de1
Revises: 001
Create Date: 2026-02-03 10:50:23.075343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5fead30de1'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_slug_key', 'events', type_='unique')
    op.drop_index('ix_events_slug', table_name='events')
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.drop_index('idx_faces_embedding', table_name='faces', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('guest_sessions', 'session_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.drop_constraint('guest_sessions_session_token_key', 'guest_sessions', type_='unique')
    op.drop_index('ix_guest_sessions_session_token', table_name='guest_sessions')
    op.create_index(op.f('ix_guest_sessions_session_token'), 'guest_sessions', ['session_token'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_guest_sessions_session_token'), table_name='guest_sessions')
    op.create_index('ix_guest_sessions_session_token', 'guest_sessions', ['session_token'], unique=False)
    op.create_unique_constraint('guest_sessions_session_token_key', 'guest_sessions', ['session_token'])
    op.alter_column('guest_sessions', 'session_token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index('idx_faces_embedding', 'faces', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.create_index('ix_events_slug', 'events', ['slug'], unique=False)
    op.create_unique_constraint('events_slug_key', 'events', ['slug'])
    # ### end Alembic commands ###
